### ISSUE TITLE
support ajax

### ISSUE THREAD

**Issue by overtrue** [simechiang/pagination.js#1]
ajax 支持不？list

建议：
- 感觉`list`命名不太好， 是不是`data`更合适呢？

**Comment by simechiang** [comment]
ajax？？？不支持，压根没考虑过。

**Comment by simechiang** [comment]
@overtrue 就是从data改成list的，: dizzy_face:  Ajax 获取数据倒是可以考虑，下一个版本先优化代码，再下一个版本准备加入。

**Comment by overtrue** [comment]
@simechiang 无语了。。。那还拿你这个干嘛？分页存在的大部分原因：数据量过大，一次展示会查询压力大，所以需要分页。如果你ajax不支持，那我真找不到使用此组件的理由了... :walking:

**Comment by simechiang** [comment]
@overtrue 哈哈，你只考虑到了PC端的情况，我现在的情况是这样的：数据量很小，只有几十条数据，而且机器网络非常不理想，外加流量有限制。所以，Ajax获取数据确实需要支持。

**Comment by overtrue** [comment]
@simechiang 哈哈，“机器网络非常不理想，外加流量有限制。所以，Ajax获取数据确实需要支持”

**Comment by simechiang** [comment]
@overtrue I hate you :unamused:

**Comment by overtrue** [comment]
@simechiang no matter.
